# conda env create|update --file environment.yml
name: toolbox
dependencies:
- python=3.6
- pip
- pip:
  - '--editable=.'
  - boto3
  - flake8
  - flake8-quotes
  - jupyter
  - matplotlib
  - numpy==1.16.*
  - pandas==0.24.1
  - pytest
  - pytest-mock
  - scipy
  - seaborn
  - sklearn
  - argparse
  - torch
  - beautifulsoup4
  - lxml
  - feedparser
